- hosts: node1:node2:node3
  user: vagrant
  tasks:
  - name: get epel-repo
    yum: name=http://download.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm state=present

  - name: install libselinux
    yum: name=libselinux-python state=present

  - selinux: policy=targeted state=permissive
  
  - name: copy mariadb repo file
    copy: src=MariaDB.repo dest=/etc/yum.repos.d/MariaDB.repo

  - name: install mariadb galera server
    yum: name=MariaDB-Galera-server state=latest

  - name: copy mariadb config file
    copy: src=galera.cnf dest=/etc/my.cnf.d/galera.cnf

- hosts: node3
  user: vagrant
  tasks:
  - name: is mysql running?
    action: shell service mysql status
    register: is_mysql_running
    ignore_errors: true

  - name: bootstrap by starting mysql with gcomm://
    action: shell service mysql start --wsrep_new_cluster
    when: is_mysql_running.rc > 0

- hosts: node2:node3
  tasks:  
  - name: if the cluster is not started already, start it
    action: service name=mysql state=started

- hosts: node3
  user: vagrant
  tasks:
  - name: Create user for MaxScale
    mysql_user: name=maxuser host="%" password=maxpwd priv=*.*:ALL state=present

  - name: Create monitoring user for MaxScale
    mysql_user: name=maxmon host="%" password=maxpwd priv=*.*:"REPLICATION CLIENT" state=present

- hosts: proxy
  user: vagrant
  tasks:
  - name: Install MaxScale
    yum: name=https://downloads.mariadb.com/files/SkySQL/MaxScale/maxscale-1.0.4-ga/RPM/centos6/maxscale-1.0.4-stable.rpm state=present
